# fly.toml file generated for vrixyz-matchbox on 2022-11-10T16:07:47+01:00

app = "vrixyz-matchbox"
kill_signal = "SIGINT"
kill_timeout = 300
processes = []

[build]
  dockerfile = "jhelsing/matchbox-server"

[env]
  PORT=3000
  RUST_LOG="debug"

[experimental]
  cmd = "export HOST=0.0.0.0:$PORT && matchbox_server"
  
[[services]]
  http_checks = []
  internal_port = 3000
  processes = ["app"]
  protocol = "tcp"
  script_checks = []

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"
    
  [[services.ports]]
    handlers = ["http"]
    port = "80"
    
  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "3s"
    interval = "15s"
    restart_limit = 0
    timeout = "10s"
